{{- $eckOperator := .Values.operatorApplications.eckOperator -}}
{{- if $eckOperator.enabled -}}
{{- if not .Values.networkPolicy.apiServerSources -}}
{{- fail "The value \"networkPolicy.apiServerSources\" must not be empty when \"operatorApplications.eckOperator.enabled\" is true" -}}
{{- end -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    labels:
        {{- include "liferay-platform.labels" $ | nindent 8 }}
    name: default-deny-ingress
    namespace: {{ $eckOperator.namespace }}
spec:
    podSelector: {}
    policyTypes:
        -   Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    labels:
        {{- include "liferay-platform.labels" $ | nindent 8 }}
    name: elastic-operator-webhook-ingress
    namespace: {{ $eckOperator.namespace }}
spec:
    ingress:
        -   from:
                {{- toYaml .Values.networkPolicy.apiServerSources | nindent 16 }}
            ports:
                -   port: https-webhook
                    protocol: TCP
    podSelector:
        matchLabels:
            app.kubernetes.io/instance: {{ $eckOperator.name }}
            app.kubernetes.io/name: elastic-operator
    policyTypes:
        -   Ingress
{{- end -}}